# Generated by Django 2.1.3 on 2019-05-01 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='owner',
        ),
        migrations.AddField(
            model_name='document',
            name='owner_id',
            field=models.IntegerField(default=-1),
            preserve_default=False,
        ),
    ]
